const { nextui } = require("@nextui-org/react");
import flowbite from "flowbite-react/tailwind";
import { addIconSelectors } from "@iconify/tailwind";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./routes/**/*.{js,ts,jsx,tsx}",
    "./public/**/*.html",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./index.html",
    "./node_modules/flowbite/**/*.js",
    "./node_modules/flowbite-react/**/*.js",
    flowbite.content(),
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  safelist: [
    "bg-blue-700",
    "hover:bg-blue-800",
    "w-64",
    "w-1/2",
    "rounded-l-lg",
    "rounded-r-lg",
    "bg-gray-200",
    "grid-cols-4",
    "grid-cols-7",
    "h-6",
    "leading-6",
    "h-9",
    "leading-9",
    "shadow-lg",
    "bg-opacity-50",
    "dark:bg-opacity-80",
  ],
  theme: {
    screens: {
      sm: "576px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
      "2xl": "1536px",
    },
    container: {
      center: true,
      padding: "1rem",
    },
    extend: {
      colors: {
        primary_flowbite: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#F5F5F5",
          950: "#172554",
          901: "#ced4dd",
        },
        bgZincFoter: "#e2e3e7",
        bgZincFoterCopyRight: "#a1a1a9",
        bgAmberBtbAdd: "#f49e0b",
        bgf3f4f6: "#f3f4f6",
        btnDeletesweetalertOk: "#a0de86",
        redCustom: "#e22920",
        customPink: "#f21260",
        veryPaleBlue: "#eef9ff",
        pastelGreen: "#a0de86",
        springGreen: {
          50: "#e1fce4",
          100: "#d2f8c7",
          200: "#a6ec9d",
          300: "#81e172",
          400: "#60d954",
          500: "#3dbf38",
          600: "#319734",
          700: "#2b7c2d",
          800: "#256f27",
          900: "#1bc24e", 
        },
         springGreenLight: "#0fc64a",
         success:"#12a150"

      },
      fontFamily: {
        sans: [
          "Be Vietnam Pro",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "4rem",
        "7xl": "5rem",
        "8xl": "4.75rem",
        "14px": "0.875rem",
        "16px": "1rem",
        "18px": "1.125rem",
        "24px": "1.5rem",
        "22px": "1.375rem",
        "46px": "2.875rem",
        normal: "1rem",
        "66px": "4.125rem",
        "30px": "1.875rem",
        "32px": "2rem",
        "34px": "2.125rem",
        "36px": "2.25rem",
        "38px": "2.375rem",
        "40px": "2.5rem",
        "42px": "2.625rem",
        "44px": "2.75rem",
        "48px": "3rem",
        "50px": "3.125rem",
        "52px": "3.25rem",
        "54px": "3.375rem",
        "56px": "3.5rem",
        "58px": "3.625rem",
        "60px": "3.75rem",
        "68px": "4.25rem",
        "70px": "4.375rem",
        "72px": "4.5rem",
        "74px": "4.625rem",
        "76px": "4.75rem",
      },
      lineHeight: {
        normal: "1.5",
        "3.625": "3.625rem",
        "8xl": "5rem",
        "80px": "80px",
        "26px": "1.625rem",
        "30px": "1.875rem",
        "32px": "2rem",
        "34px": "2.125rem",
        "36px": "2.25rem",
        "38px": "2.375rem",
        "40px": "2.5rem",
        "42px": "2.625rem",
        "44px": "2.75rem",
        "46px": "2.875rem",
        "48px": "3rem",
        "50px": "3.125rem",
        "22px": "1.375rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        bold: "700",
        600: "600",
      },
      spacing: {
        "1/3": "33.333%",
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
        "top-12": "3rem",
        "top-16": "4rem",
        "top-32": "8rem",
        "top-48": "12rem",
        "top-64": "16rem",
        "top-80": "20rem",
        "top-96": "24rem",
        "left-10": "2.5rem",
        "left-1/2": "50%",
        100: "100px",
        "-72px": "-72px",
        "-10px": "-10px",
        "-60px": "-60px",
        "200px": "200px",
      },
      borderWidth: {
        half: "0.5px",
      },
      transitionProperty: {
        width: "width",
      },
      textDecoration: ["active"],
      minWidth: {
        kanban: "28rem",
      },
      maxWidth: {
        "8xl": "90rem",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "fade-in": "fadeIn 200ms ease-in-out",
      },
      boxShadow: {
        "lg-light":
          "0 10px 15px -3px rgba(255, 255, 255, 0.1), 0 4px 6px -2px rgba(255, 255, 255, 0.05)",
      },
    },
  },
  plugins: [
    flowbite.plugin(),
    addIconSelectors(["mdi-light", "mdi", "solar"]),
    nextui({
      themes: {
        light: {
          colors: {
            background: "#FFFFFF", 
            foreground: "#11181C", 
            primary: {
              foreground: "#FFFFFF",
              DEFAULT: "#006FEE",
            },
            customChipColor: "#FF5733"
          },
        },
        dark: {
          colors: {
            background: "#000000",
            foreground: "#ECEDEE",
            primary: {
              foreground: "#FFFFFF",
              DEFAULT: "#006FEE",
            },
            customChipColor: "#FF5733"
          },
        },
      },
    }),
  ],
};
