const Auth = {
  AUTH_UPDATE: "AUTH_UPDATE",
  USE_INFO: "USE_INFO",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};

export default Auth;
