const googleRouter = require("./authGoogle");
const authRouter = require("./auth");
const userRouter = require("./user");
const productRouter = require("./admin/product/product");
const userRoutes = require("./admin/auth/userRoutes");
const brandRouter = require("./admin/brands/brands");
const CartRouter = require("./product/cart");
const supplierRoutes = require("./admin/suppliers/suppliers");
const adminProduct = require("./admin/product_v2");
const adminPost = require("./admin/post");
const adminProductAuction = require("./admin/productAuction");
const adminAttributes = require("./admin/attributes");
const clientProduct = require("./client/product");
const clientProductDetail = require("./client/product-detail");
const clientProductDetailAuction = require("./client/detailAuction");
const clientAuction = require("./client/AuctionWinsByUser");
// const productRouter_v2 = require("./admin/product_v2");
const inboundRouter = require("./admin/inboundshipments/inbound");
const inventoryRouter = require("./admin/inventory");
const clientSidebarAuction = require("./client/sidebar/auction");
const clientSidebarProduct = require("./client/sidebar/product");
const attributesRouter = require("./attributes");
const clientCategory = require("./client/category");
const WathListRouter = require("./product/product");
const orderCart = require("./client/orders/order");
const Contact = require("./client/contact/contact");
// const supplierRoutes = require("./admin/suppliers/suppliers");
// const WathListRouter = require("./product/product");

const vnPayRouter = require("./admin/vnpay/order");
const vnPayAuctionRouter = require("./admin/vnpayAuction/order");
const randBidRouter = require("./admin/randBid/randBid.routes");
const biddingRouter = require("./client/bidding/bidding.routes");
const auctionsRouter = require("./client/auctions/auctions.routes");
const orderAucRouter = require("./client/orderAndDetail/orderAndDetail.routes");
const orderDetailAuction = require("./client/details/orderDetail.routes");
const customerServiceRouter = require("./client/customer-service/deleteBidding.routes");
const notificationRouter = require("./client/notification/notification.routes");
const interactionRouter = require("./client/interaction/interation.routes");
const orderdetails = require("./client/orders/OrderDetail");
const OrderAd = require("./admin/order/orderAd");
const momoRouter = require("./client/momo/momo");
const orderAucIteraction = require("./client/iterationOrderAuct/iterationOrderAuc.routes");

const commentAdminRouter = require("./admin/comment");
const commentClientRouter = require("./client/comment");
const bankRouter = require("./client/bank");
const statistical = require("./admin/statistical");
const recommendationRoute = require("./client/recommendation/recommendation");
const bestSellRoute = require("./client/best-selling/best-selling");

const routes = (app) => {
  app.use("/api/admin/statistical", statistical);

  app.use("/api/auth", authRouter);
  app.use("/api/auth", googleRouter);
  app.use("/api/user", userRouter);
  app.use("/api/product", productRouter);
  app.use("/api/admin", userRoutes);
  app.use("/api/suppliers", supplierRoutes);
  app.use("/api/cart", CartRouter);
  app.use("/api/admin/product", adminProduct);
  app.use("/api/admin/post", adminPost);
  app.use("/api/admin/productAuction", adminProductAuction);
  app.use("/api/admin/attributes", adminAttributes);
  app.use("/api/client/product", clientProduct);
  app.use("/api/client/product-detail", clientProductDetail);
  app.use("/api/client/product-detail-auction", clientProductDetailAuction);
  app.use("/api/client/auction", clientAuction);

  app.use("/api/client/sidebar/auction", clientSidebarAuction);
  app.use("/api/attributes", attributesRouter);
  app.use("/api/client/sidebar/product", clientSidebarProduct);
  app.use("/api/brands", brandRouter);
  app.use("/api/wathlist", WathListRouter);
  // app.use("/api/auctions", auctionRouter);
  app.use("/api/inbound", inboundRouter);
  app.use("/api/inventory", inventoryRouter);
  app.use("/api/vnpay", vnPayRouter);
  app.use("/api/vnpayAuction", vnPayAuctionRouter);
  app.use("/api/order", orderCart);
  app.use("/api/admin/randBid", randBidRouter);
  app.use("/api/client/bidding", biddingRouter);
  app.use("/api/client/auctions", auctionsRouter);
  app.use("/api/client/category", clientCategory);
  app.use("/api/client/orderAuc", orderAucRouter);
  app.use("/api/client/orderDetailAuc", orderDetailAuction);
  app.use("/api/client/customer-service", customerServiceRouter);
  app.use("/api/notification", notificationRouter);
  app.use("/api/interaction", interactionRouter);
  app.use("/api/client/contact", Contact);
  app.use("/api/orderdetails", orderdetails);
  app.use("/api/admin/order", OrderAd);
  app.use("/api/momo", momoRouter);
  app.use("/api/admin/comment", commentAdminRouter);
  app.use("/api/client/comment", commentClientRouter);
  app.use("/api/client/iteracOder", orderAucIteraction);
  app.use("/api/bank", bankRouter);
  app.use("/api/client/recommendation", recommendationRoute);
  app.use("/api/client/best-selling", bestSellRoute);
};

module.exports = routes;
