export const labels: Record<string, string> = {
  account: "Tài khoản",
  supplier: "Nhà cung cấp",
  brand: "Thương hiệu",
  recycleBin: "Thùng rác",
  categories: "Danh mục",
  comment: "Tương tác",
  homeAdmin: "Trang chủ",
  product: "Sản phẩm",
  inbound: "Nhập hàng",
  orderCart: "Đơn hàng",
  orderAuction: "Đơn hàng đấu giá",
  post: "Bài viết",
  attribute: "Biến thể",
  auctions: "Đấu giá",
};
