import { combineReducers } from "@reduxjs/toolkit";
import {
  listSclice,
  softDeleteSlice,
  addSlice,
  getOneSlice,
  updateSlice,
  paginatedProductSlice,
  deletedProductSlice,
  addVariantSlice,
  LimitProductAuctionSlice,
  softDeleteAuctionSlice,
  getOneAuctionSlice,
  getVariantColorsByIdSlice,
  addImageVariantSlice,
  getVariantsByProductIdSlice,
  deleteVariantSlice,
  editVariantSlice,
  getOneProductVariantSlice,
  selectSupplierSlice,
  selectDiscountSlice,
  selectConditionShoppingSlice,
  selectCategoriesSlice,
  selectBrandSlice,
  getImageByVariantIdSlice,
  deleteImageVariantSlice,
  getOneImageVariantSlice,
  editImageVariantSlice,
  getDeleteListAuctionSlice,
  hardDeleteAuctionSlice,
  restoreAuctionSlice
} from "src/redux/product/admin/Slicle";
const productsReducer = combineReducers({
  list: listSclice,
  softDelete: softDeleteSlice,
  softDeleteAuction: softDeleteAuctionSlice,
  add: addSlice,
  addVariant: addVariantSlice,
  getone: getOneSlice,
  update: updateSlice,
  pagilistActive: paginatedProductSlice,
  pagiDeletedList:deletedProductSlice,
  LimitProductAuction:LimitProductAuctionSlice,
  getOneAuction:getOneAuctionSlice,
  getVariantColorsById:getVariantColorsByIdSlice,
  addImageVariant:addImageVariantSlice,
  getVariantsByProductId:getVariantsByProductIdSlice,
  deleteVariant:deleteVariantSlice,
  editVariant:editVariantSlice,
  getOneProductVariant:getOneProductVariantSlice,
  selectSupplier: selectSupplierSlice,
  selectDiscount: selectDiscountSlice,
  selectConditionShopping: selectConditionShoppingSlice,
  selectCategories: selectCategoriesSlice,
  selectBrand: selectBrandSlice,
  getImageByVariantId: getImageByVariantIdSlice,
  deleteImageVariant:deleteImageVariantSlice,
  getOneImageVariant:getOneImageVariantSlice,
  editImageVariant:editImageVariantSlice,
  getDeleteListAuction:getDeleteListAuctionSlice,
  hardDeleteAuction:hardDeleteAuctionSlice,
  restoreAuction:restoreAuctionSlice

});

export default productsReducer;
